### ISSUE TITLE
Qt Application (event loop) tasks

### ISSUE THREAD

**Issue by fmoo** [facebook/sparts#14]
Add two modules to sparts.tasks:

• qt
• qt_pyside

These will both define QApplicationTask, QCoreApplicationTask.

Overridable _makeApplication

initTask() does self.application = self._makeApplication()

_runloop just calls self.application.exec_()

stop calls self.application.exit()

Catch the application close signal and call self.service.shutdown()

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by fmoo** [comment]
Unfortuantely qt's threading model just doesn't play nicely with sparts.

While glib/gtk is less python/user friendly, we've had much more success with it.
