### ISSUE TITLE
Support python3

### ISSUE THREAD

**Issue by fmoo** [facebook/sparts#32]
Not sure what this will take, but it will probably be a nightmare.  To support _all_ of sparts means twisted and tornado need to be py3 ready.

**Comment by ryanrhee** [comment]
Tornado works with Py3.
There's also Py3 Thrift.
I can see an argument for dropping Twisted support.

**Comment by fmoo** [comment]
Twisted is optional.  Also, if I recall correctly, twisted-13+ works with Python 3.3 and above.

**Comment by fmoo** [comment]
@ryanrhee - does Apache thrift support Python 3 also?  Or is it just fbthrift?

**Comment by ryanrhee** [comment]
oh it may just be fbthrift - not sure.
