### ISSUE TITLE
enforce dependency on six >= 1.5

### ISSUE THREAD

**Issue by chantra** [facebook/sparts#96]
Apparently the queue module made it somewhere around 1.5.0 and is required by sparts. in facebook/augmented-traffic-control#74 the user is most likely having an old version on their system so it fail to start up. Given #90 I am not sure it is worth it, but should the version dependency be enforced in setup.py? Happy to send a diff your way if needs be,

**Comment by fmoo** [comment]
Ok, done.  Do we need a (0.7.2) release to pin atc to?

**Comment by chantra** [comment]
no, not worth a new release. I just wanted to flag it as a dependency.

**Comment by zhangxiaang** [comment]
@chantra my 'six' version is lower than 1.5
then how can i update 'six' to 1.5 or Higher？
thank u very much!

**Comment by zhangxiaang** [comment]
..thanks!!!
i have resolved it by 
``` 
sudo pip install six --upgrade
```
